### ISSUE TITLE
Support SAP Push Channel Protocol (PCP)

### ISSUE THREAD

**Issue by oklemenz2** [cap-js-community/websocket#2]
UI5 Implementation:
https://github.com/SAP/openui5/blob/fb0c4e2a658205d5025f61f8502c496ef988fe19/src/sap.ui.core/src/sap/ui/core/ws/SapPcpWebSocket.js#L111

UI5 documentation:
https://ui5.sap.com/#/api/sap.ui.core.ws.SapPcpWebSocket

Example implementation:
https://btp.udina.de/development/websocket.html#sap-push-channel-protocol-pcp

**Comment by oklemenz2** [comment]
This is implemented with ws 1.2.0:
https://github.com/cap-js-community/websocket/releases/tag/v1.2.0
Please check.

**Comment by hschaefer123** [comment]
Thanks Oliver,

i will try to add this plug to my CAP Portal as soon, as the Notification plug is v8 compatible.

Regards
Holger
