### ISSUE TITLE
VS Code: Page Map cannot be opened

### ISSUE THREAD

**Issue by stefannothaft** [cap-js-community/websocket#6]
Hello, 
I've already posted a question there: https://community.sap.com/t5/technology-q-a/vs-code-page-map-cannot-be-opened/qaq-p/13895469 
But, maybe it is better to ask it also here: If I open the Page Map, I have received the error "unknown protocol". I also noticed that in the cs-plugin.js the protocols are registered. Somehow it doesn't work yet for the page map...

Thank you.

**Comment by oklemenz2** [comment]
I have no solution for this yet. I will clarify this internally with the CAP colleagues.. Please stay tuned.

**Comment by oklemenz2** [comment]
Do you annotate the service via `@protocol: 'ws'`?
Can you try to use `@ws` on service level?

**Comment by stefannothaft** [comment]
yes, I've used `@protocol: 'ws'`

With `@ws` on service level the pagemap works again. Thank you!
